#!/bin/bash

_docker_image=${PWD##*/}

_default_ip=$(ip addr show $(ip route | awk '/default/ { print $5 }') | grep "inet" | head -n 1 | awk '/inet/ {print $2}' | cut -d'/' -f1)
_args="--net=host -e HOST=$_default_ip "

if [ -d "/dev/dri" ]; then
  _args+="--device /dev/dri:/dev/dri -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -e HAS_GPU=1"
fi

if [ -d "/dev/accel" ]; then
  _args+=" --device /dev/accel:/dev/accel -e HAS_NPU=1"
fi

docker run -it --rm --security-opt seccomp=unconfined -v `pwd`:/project -v gguf-model-volume:/models -w /project -e HUGGINGFACE_TOKEN=$HUGGINGFACE_TOKEN $_args $_docker_image $@
